### ISSUE TITLE
AttributeError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.

### ISSUE THREAD

**Issue by HzfFrank** [mitsuba-renderer/drjit-core#65]
Hi, as https://github.com/rgl-epfl/differentiable-sdf-rendering/issues/21 mentioned, I met such error about jit and cuda:
```
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 107, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "optimize.py", line 108, in <module>
    main(sys.argv[1:])
  File "optimize.py", line 78, in main
    mi.set_variant('llvm_ad_rgb' if use_llvm else 'cuda_ad_rgb')
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 317, in set_variant
    _import('mitsuba.ad.integrators')
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/python/ad/__init__.py", line 1, in <module>
    from .integrators import *
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/python/ad/integrators/prb_basic.py", line 6, in <module>
    from .common import RBIntegrator
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 253, in __getattribute__
    result = module.__getattribute__(key)
  File "/home/username/anaconda3/envs/diff-sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 115, in __getattribute__
    raise AttributeError(e)
AttributeError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.
```
Here is how it shows when I
`nvcc -V`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
`nvidia-smi`
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 531.41       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 L...    On | 00000000:01:00.0  On |                  N/A |
| N/A   38C    P8                6W /  N/A|    358MiB /  4096MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
Is there any thing wrong with my cuda?
How can I `initialize the CUDA backend`?
I'll appreciate it lot if someone can help with it.

**Comment by merlinND** [comment]
Hello @HzfFrank,

Do you encounter the same issue with the latest version of the `mitsuba` package, when installed with `pip install mitsuba`?

**Comment by HzfFrank** [comment]
> Hello @HzfFrank,
> 
> Do you encounter the same issue with the latest version of the `mitsuba` package, when installed with `pip install mitsuba`?

Thank you for your concern with my issue, I solved it now but still don't understand the cause of the problem
I followed my friend's way to reconfigure the environment, now it shows when I
`nvcc-V`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```
`nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:08.0 Off |                    0 |
| N/A   29C    P8    11W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
and my `mitsuba` version is 3.1.1
I am still confused about this issue `the CUDA backend hasn't been initialized`
But anyway, I was lucky enough to solve this problem now, thank you for your concern with my issue

**Comment by njroussel** [comment]
Hi @HzfFrank 

Happy that your issue was resolved.

> I followed my friend's way to reconfigure the environment, 
For posterity, I'd appreciate if you could give a bit more details about the steps you took. You never know, someone else could encounter the same issue.

I'll close the issue.
